[Do not merge]: handle case where mms could not be retrieve
ubports/telephony-service pull request #13
Opened 2020-10-29 11:02 UTC by lduboeuf

2020-11-11 18:23 UTC, Flohack74 requested changes

2020-11-11 18:23 UTC, Flohack74 commented on indicator/textchannelobserver.cpp
> +        } else if (attachmentCount == 0) {
You have before attahcmentCount > 0, so now the elseif can be just else or? There will be no sane way that attachmentcount is smaller than 0 :) -so please make it unconditional else only.

2020-11-11 18:23 UTC, Flohack74 commented on indicator/textchannelobserver.cpp
> +            messageText = QString::fromUtf8(C::gettext("Oops, there has been an error with the MMS system and this message could not be retrieve. Please ensure Cellular Data is ON and MMS settings ar
typo: retrieveD

2020-11-11 20:45 UTC, lduboeuf commented
@Flohack74 note that there is no translation up in weblate for telephony-service afaik

2020-11-11 20:59 UTC, Flohack74 approved these changes

2020-11-23 09:53 UTC, Flohack74 commented
Ok we will put smth on Weblate thx!

2020-11-23 09:53 UTC, Flohack74 approved these changes

2020-11-26 10:56 UTC, merged

2020-12-05 16:58 UTC, jezek commented
Device: FP2
OS: 2020-W49

On failed MMS deliver*, in the notification bubble there is a text "Oops, ...". Clicking on the bubble opens ```messaging-app``` focused on the sender conversation's latest message, which (in this failed case) is the "Oops, ..." text with red exclamation mark (:exclamation: ) in circle + vertical stripe on the left of the text.