PhoneUtils: Add method to get the country prefix from a locale string
ubports/telephony-service pull request #29
Opened 2021-04-14 07:59 UTC by lduboeuf

2021-04-14 21:37 UTC, lduboeuf commented
humm i need to make it more easy to use at QML side.

2021-05-25 22:27 UTC, UniversalSuperBox requested changes
It would be nice to add a small test of its functionality to https://github.com/ubports/telephony-service/blob/27e0a35c4ab6f53b71ab7ba57d693cc373f30783/tests/Ubuntu.Telephony/tst_PhoneNumberPhoneUtils.qml

2021-05-26 15:59 UTC, lduboeuf commented
@UniversalSuperBox : done

2021-05-26 17:53 UTC, UniversalSuperBox approved these changes

2021-05-26 17:53 UTC, merged