Remove unused platfrom apis
ubports/telephony-service pull request #4
Opened 2020-02-04 19:08 UTC by mariogrip

Seems to be not needed anymore as we currently does not even install the platform apis

@bhush9

2020-02-05 14:37 UTC, bhush9 commented
Checks are failing but this looks good to me.

2020-02-05 19:28 UTC, UniversalSuperBox requested changes

2020-02-05 19:28 UTC, UniversalSuperBox commented on libtelephonyservice/applicationutils.cpp
> +        QDesktopServices::openUrl(url);
No apps open from the indicator with this patch installed.

2020-02-19 04:52 UTC, bhush9 commented on CMakeLists.txt
>  pkg_check_modules(UserMetrics REQUIRED libusermetricsinput-1)
This should  removed from here.

2020-02-20 20:14 UTC, UniversalSuperBox approved these changes
Messaging menu, with direct replies, tests fine here.

2020-02-20 20:14 UTC, merged